### ISSUE TITLE
Do it for ASSEMBLY !!

### ISSUE THREAD

**Issue by judemont** [AsteroidusTv/CNPS-Rust#1]

**Comment by AsteroidusTv** [comment]
Give me the layout for assembly

**Comment by judemont** [comment]
section .data
    prompt db 'Entrez la valeur de n : ', 0
    output db 'Suite de Fibonacci : ', 0
    newline db 10, 0

section .bss
    n resb 2

section .text
    global _start

_start:
    mov eax, 4
    mov ebx, 1
    mov ecx, prompt
    mov edx, 26
    int 0x80

    mov eax, 3
    mov ebx, 0
    mov ecx, n
    mov edx, 2
    int 0x80

    xor eax, eax
    mov al, byte [n]
    sub eax, 0x30

    mov ebx, 0
    mov ecx, 1
    mov edx, eax
    add edx, 1

    mov eax, 4
    mov ebx, 1
    mov ecx, output
    mov edx, 18
    int 0x80

.fib_loop:
    mov eax, ebx
    mov ebx, 1
    add ebx, ecx

    mov ecx, eax

    mov eax, 4
    mov ebx, 1
    mov edx, 2
    int 0x80

    mov eax, 4
    mov ebx, 1
    mov ecx, newline
    mov edx, 1
    int 0x80

    dec edx
    jnz .fib_loop

    mov eax, 1
    xor ebx, ebx
    int 0x80

**Comment by AsteroidusTv** [comment]
the layout is how the files are organized Ex. rust
project-name 
    src 
        main.rs
    cargo.toml

**Comment by AsteroidusTv** [comment]
The layout is how files are organized !

**Comment by judemont** [comment]
You __Realy__ want to know how assembly files are organised ?

No... I dont thing, you are ready...

**Comment by AsteroidusTv** [comment]
The assembly has been added in supported languages. Thank you for your feedback!
