### ISSUE TITLE
Load indefinitely 

### ISSUE THREAD

**Issue by judemont** [AsteroidusTv/CNPS-Rust#3]
When i run the .deb application, I have this screen for 10 years: 
![Capture d’écran du 2023-08-08 13-59-09](https://github.com/AsteroidusTv/CNPS-Rust/assets/96385330/ff7db25e-6df7-441b-9c39-35d951623629)

**Comment by AsteroidusTv** [comment]
The new version is supposed to resolve this issue

**Comment by judemont** [comment]
"Supposed"😨
